package cn.lemwood.theme

import androidx.compose.ui.graphics.Color

// Light theme tokens
internal val md_theme_light_primary = Color(0xFF1565C0)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFD1E4FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
internal val md_theme_light_secondary = Color(0xFF00897B)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFB2DFDB)
internal val md_theme_light_onSecondaryContainer = Color(0xFF00201D)
internal val md_theme_light_error = Color(0xFFE53935)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFF8F9FE)
internal val md_theme_light_onBackground = Color(0xFF1A1C23)
internal val md_theme_light_surface = Color(0xFFFFFFFF)
internal val md_theme_light_onSurface = Color(0xFF1A1C23)
internal val md_theme_light_surfaceVariant = Color(0xFFF0F2F8)
internal val md_theme_light_onSurfaceVariant = Color(0xFF41474D)
internal val md_theme_light_outline = Color(0xFFB0B7C4)
internal val md_theme_light_outlineVariant = Color(0xFFC4C6CF)

// Dark theme tokens
internal val md_theme_dark_primary = Color(0xFF64B5F6)
internal val md_theme_dark_onPrimary = Color(0xFF00325A)
internal val md_theme_dark_primaryContainer = Color(0xFF00497D)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFD1E4FF)
internal val md_theme_dark_secondary = Color(0xFF4DB6AC)
internal val md_theme_dark_onSecondary = Color(0xFF003733)
internal val md_theme_dark_secondaryContainer = Color(0xFF00504A)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFB2DFDB)
internal val md_theme_dark_error = Color(0xFFEF5350)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF111318)
internal val md_theme_dark_onBackground = Color(0xFFE1E2E9)
internal val md_theme_dark_surface = Color(0xFF1A1C23)
internal val md_theme_dark_onSurface = Color(0xFFE1E2E9)
internal val md_theme_dark_surfaceVariant = Color(0xFF262931)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
internal val md_theme_dark_outline = Color(0xFF8E9099)
internal val md_theme_dark_outlineVariant = Color(0xFF44474E)

// Semantic status colors
val OnlineColor = Color(0xFF4CAF50)
val OfflineColor = Color(0xFF9E9E9E)
val ConnectingColor = Color(0xFFFFA726)
val ErrorColor = Color(0xFFE53935)
val UploadTrafficColor = Color(0xFF42A5F5)
val DownloadTrafficColor = Color(0xFF66BB6A)
